#! /bin/sh
### BEGIN INIT INFO
# Provides: quake-server
# Required-Start: $local_fs $remote_fs
# Required-Stop: $local_fs $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: S 0 1 6
# Short-Description: Quake 3 Game Server
# Description: Starts Quake 3 Game Server as a daemon, and stops/starts it on reboot, startup, and shutdown
# Author: nicholas.r@gmail.com
# Licence: GPL2
### END INIT INFO

# User to run quake server as
QUAKE_USER=quake
QUAKE_GROUP=quake

# Location of minecraft files
LOCATION=/opt/quake-server

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DESC="Quake Game Server"
DAEMON=/opt/quake-server/q3ded
ARGS="+set dedicated 2 +exec server.cfg"
SCRIPTNAME=/etc/init.d/quake-server

# Exit if the package is not installed
if [ ! -x "$DAEMON" ]; then
{
echo "Couldn't find $DAEMON"
exit 99
}
fi

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
do_start()
{
# Return
# 0 if daemon has been started
# 1 if daemon was already running
# 2 if daemon could not be started
start-stop-daemon --start --quiet --background --chuid $QUAKE_USER:$QUAKE_GROUP -d $LOCATION --exec $DAEMON --test > /dev/null \
|| return 1
start-stop-daemon --start --quiet --background --chuid $QUAKE_USER:$QUAKE_GROUP -d $LOCATION --exec $DAEMON -- $ARGS \
|| return 2
}

#
# Function that stops the daemon/service
#
do_stop()
{
# Return
# 0 if daemon has been stopped
# 1 if daemon was already stopped
# 2 if daemon could not be stopped
# other if a failure occurred
start-stop-daemon --stop --signal 2 --retry 5 --quiet --name $DAEMON
RETVAL="$?"
[ "$RETVAL" = 2 ] && return 2
return "$RETVAL"
}

case "$1" in
start)
log_daemon_msg "Starting $DESC"
do_start
case "$?" in
0|1) log_end_msg 0 ;;
2) log_end_msg 1 ;;
esac
;;
stop)
log_daemon_msg "Stopping $DESC"
do_stop
case "$?" in
0|1) log_end_msg 0 ;;
2) log_end_msg 1 ;;
esac
;;
restart)
log_daemon_msg "Restarting $DESC"
do_stop
case "$?" in
0|1)
do_start
case "$?" in
0) log_end_msg 0 ;;
1) log_end_msg 1 ;; # Old process is still running
*) log_end_msg 1 ;; # Failed to start
esac
;;
*)
# Failed to stop
log_end_msg 1
;;
esac
;;
*)
echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
exit 3
;;
esac

